### ISSUE TITLE
Rename command to /lead

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#16]
I'm wondering what is more suited to this. Considering we would be using `/add-lead` for both ADD and EDIT, I'm wondering if `/lead` is more suited. This is low prio and can be after MVP, or whenever suits to discuss / implement.

* `/lead` => ADD
* `/lead UNIQUE_ID` => EDIT

I'll add another issue for the UNIQUE_ID format `${company_name}-#${tech-role}-${INT_AUTO_INCREMENT}` and display

**Comment by jacekelgda** [comment]
#19 might eliminate the need of `command id` but renaming command is quite easy

New spec:

rename command to `/lead`

**Comment by mccrodp** [comment]
We might postpone this until we discuss https://github.com/jacekelgda/cavalry-bot/issues/17#issuecomment-369764156

**Comment by mccrodp** [comment]
>Sure, let's use the simple "Edit" button for the MVP, when this scales and we have a clearer picture how it's working in the wild, we can spec a more sustainable solution in the long run if the CMD-F proves to be insufficient. Feel free to close this for now if that's all good.

We can leave it at `/add-lead` for now as we will use an Edit button. Closing this.
