### ISSUE TITLE
Add unique lead id to post to allow copy and paste as edit command param

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#17]
If we auto generate the unique id of the format: `${company_name}-#${tech-role}-${INT_AUTO_INCREMENT}` we can post it to the #cavalry channel at the top or bottom of the lead (maybe top?). then we can use it as a param to the command easily to populate the form with the lead details and have access to change and save, updating the lead :)

**Comment by mccrodp** [comment]
I wonder is there value for both, perhaps not, but we'll leave open to have a think on that for now.

**Comment by jacekelgda** [comment]
Where do you get the ide from ? I imagine you would have to scroll somewhere to copy ? There is a pinned list and search functionality for ease of access to any message in the channel. Wouldn't simple edit button be more then enough for this ?

**Comment by mccrodp** [comment]
You mean Slack default search? I think in future it might be useful to have an `/edit-lead` command to bring up a dialog with all leads and we can click into them to edit specific ones, but for now, let's leave it as a button on each thread. This is fine for current volume, but will be an issue when volume increases significantly. I'm talking about that extra 5 seconds, that could potentially be 2 seconds if we have an `/edit-lead` dialog. When doing this on repeat daily, it adds up.

So, with that in mind, "Edit" button and `/lead` still make the most sense? I can create an issue for future for `/edit-lead` if that's the case, unless you have any other suggestion there.

**Comment by jacekelgda** [comment]
Let's backtrack in here and work together ;)

The original requirement in here was to do readable id for ease of reference: In example, `move-37-ai_node-developer-#1` - each role title would be converted into something like that. We will need the number in the end as we will get duplicates sooner or later. I think this format still is not easy enough to reference by heart. Instead, you will need to search the lead somewhere ( most likely in slack channel history ) to copy that id to paste into the command - so if you already found that lead in slack channel history ( using cmd+f )you are just one click away from editing.

Then you proposed additional `/edit-lead` command which will bring the options list of all leads. In case there is a lot of them you still will either have to scroll through it or search for it. It's a better idea but also quite a difficult workflow. Comparing to using a built-in functionalities slack has.

If you kind of know what you are looking for you might just use the shortcut `cmd+f` which focuses you on search bar with an already selected scope of the channel. Then you search `move37 node developer` and you should get that lead in the first hit. It requires no development and it's quite functional.

**Comment by mccrodp** [comment]
Sure, let's use the simple "Edit" button for the MVP, when this scales and we have a clearer picture how it's working in the wild, we can spec a more sustainable solution in the long run if the CMD-F proves to be insufficient. Feel free to close this for now if that's all good.
