### ISSUE TITLE
Edit existing lead

### ISSUE THREAD

**Issue by jacekelgda** [jacekelgda/cavalry-bot#19]
It should be able to bring the dialog for the specific existing lead post to edit. It needs to show pre-filled data from the original. It should be possible to edit and save.

For this we might do a hack for interactive buttons, not providing any response to remove it after the interaction. That way button stays. Anyone will be able to click it so we need to add some validation for who is actually allowed to edit - but since this will be in a core team group anyway it should not be a huge deal.

**Comment by mccrodp** [comment]
Sounds good, but as long as the endpoint has some validation so nobody can hack that. Plus, it might be time to move this over to a private repo.

**Comment by mccrodp** [comment]
We should create a follow up issue once we have confirmation on this one, for adding a list of authorised edit users, maybe even the button does not display for users not in authorised list.

**Comment by jacekelgda** [comment]
Not showing the button is not possible @mccrodp. It's a slack limitation - message is shown to everyone in the same way.

**Comment by jacekelgda** [comment]
#20 will provide security for this
