### ISSUE TITLE
Secure access to /lead related commands

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#20]
Only people in core team should have access to these commands. How will endpoints be secured also?

**Comment by RafalWilinski** [comment]
This could be easily achieved using env variable containing a comma separated list of authorized users. I can do that.

**Comment by RafalWilinski** [comment]
Addressed here: https://github.com/jacekelgda/cavalry-bot/pull/28

**Comment by jacekelgda** [comment]
@mccrodp are you referring to our API endpoints? We have a validation token which is configured in slack application. So no external requests can pass. This token is secret.

**Comment by mccrodp** [comment]
I was thinking that perhaps the `/lead` command doesn't even show as an option for non-core users. Is that tricky at the moment? I would have thought Slack just provides an access control for commands / bots, but if difficult, we just make it so that non-core users don't see the dialog if they select the command? It just returns a `Insufficient Privileges` or similar error message.

**Comment by jacekelgda** [comment]
It’s not possible to entirely hide a command to some users. We can do validation logic on our end after someone runs a command.

**Comment by mccrodp** [comment]
Sounds like the best we can do, sounds good if we proceed with that. Non-auth users should have read/write access to the associated DB either way 😄 👍

**Comment by jacekelgda** [comment]
This is resolved in https://github.com/jacekelgda/cavalry-bot/pull/28/files and refactored in https://github.com/jacekelgda/cavalry-bot/pull/36
