### ISSUE TITLE
Provide a way to "Archive" a lead

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#22]
When a lead goes stale I would like to be able to archive it. I am not sure what the best way to do that is. Perhaps a field on the lead for "Active" / "Archive".

In this case when we create a lead, they are "Active" by default, but when we "Archive" a lead: 

1. no longer send out the notifications for that lead
2. unpin the lead from the channel

In the case that the lead comes back up, we can make it "Active" again and update it if necessary, and the notifications restart.

**Comment by jacekelgda** [comment]
We can provide this in edit view. Button or a checkbox ( if possible ) or a dropdown ( active / archived )

**Comment by mccrodp** [comment]
I also think it should be possible to achieve the same function via the bizdev notification. A "Lost Deal" option or similar which 

* Archives it (set `archive` value to `TRUE` or similar)
* sends a message to the thread notifying of lost (I've an idea also for extra detail, will create issues)
* Unpins the message from the channel
* Notified original lead creator, bizdev responsible and lead updator
