### ISSUE TITLE
Remove `New lead` text prior to channel posting

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#33]
To have more information "Bizdev", "Role", "Partner" and "Status" above the fold when the post is pinned, let's remove the "New Lead:" text entirely.

**Comment by RafalWilinski** [comment]
You mean to replace `pretext` with `${Bizdev} ${Role} ${Partner} ${Status}`?

**Comment by mccrodp** [comment]
Sure, or just no `pretext` at all. If we need pretext, perhaps it can be in bold: 

`*${Partner}: ${Role} - ${Bizdev} - ${Status}*`

<img width="222" alt="screen shot 2018-03-09 at 09 55 37" src="https://user-images.githubusercontent.com/559938/37184738-4832cffa-2380-11e8-8050-358573d9450a.png">

So, you see that Bizdev and status are chopped, if no pretext, I think we'll see everything we need by default?
