### ISSUE TITLE
Change status string "Waiting for update" to "New lead"

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#34]
This will clarify the status more clearly that a lead is just in and that is the current status, rather than we are waiting for a status.

**Comment by mccrodp** [comment]
I just thought, if after a status message has been sent to bizdev, we could append "Update Pending" to the latest status. Eg. -

* Lead is created it gets "New lead" status
* 1 week later notification gets sent out, the status is the same, but the pinned post shows : "New lead (Update Pending)"
* Bidev then update it and it goes to "Still discussing, but positive"
* 1 week later another update message is sent out, status remains, but display is now "Still discussing, but positive (Update Pending)"
* Bizdev update to "Desperately need devs" and so on

How does that sound? The status options do not change, just the UI provides more information on the status.

**Comment by jacekelgda** [comment]
@mccrodp good idea on update pending status - could you create a separate issue for this ?

**Comment by mccrodp** [comment]
Done https://github.com/jacekelgda/cavalry-bot/issues/37
