### ISSUE TITLE
Template based lead description

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#39]
When I create new lead the dialog textarea for description should already contain a template:

```
SHORTLIST: %shortlist,
TIMEZONE: %timezone,
RATE: %rate 
```

**Comment by jacekelgda** [comment]
That's a good idea @mccrodp 
We can offer a type of template which already exists in lead description to follow the same format. How does that sound ?

**Comment by mccrodp** [comment]
Perfecto, let's do that and then we can always extract data programmatically, if needed, if people follow the template. Cheers 😄
