### ISSUE TITLE
CavalryBot not submitting new leads to channel

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#46]
I tried to create a lead there and got an error after clicking submit:

>We had some trouble connecting. Try again?

The next time I didn’t fully populate the main textarea description field. It submitted successfully but disappeared into the ether. I don’t see a post on a channel.

**Comment by karolsojko** [comment]
@jacekelgda can we get any logs for this ?

**Comment by karolsojko** [comment]
Look for logs aroun 9:03 am
