### ISSUE TITLE
Discuss extraction of values from the template

### ISSUE THREAD

**Issue by mccrodp** [jacekelgda/cavalry-bot#51]
Now that we have the template. Are we storing these values in their own columns in the DB at the moment?

```
SHORTLIST: %shortlist,
TIMEZONE: %timezone,
RATE: %rate
```

This is not 100% essential just yet, but wonder if we're already doing it. It will be useful as we grow though.

On a related note, I'd like to be able to add a tags field, but as we're at the limit, perhaps it can be part of this template and just be a CSV field, if that doesn't mess up the formating of the rest of the template. Eg.

```
SHORTLIST: %shortlist,
TIMEZONE: %timezone,
RATE: %rate
TAGS: %tech1, %tech2, %tech3
```

For this, it would be good to store in a DB column. We have a partner trends doc, it's manual at the moment, but this will allow for automation to track trends. Any thoughts or suggestions?

**Comment by karolsojko** [comment]
@mccrodp we are storing everything from the description field as `key: value` in a given record. So you can add as many fields as you want as long as you follow the template pattern.

We don't support breaking values by coma and storing them separately but this can be adjusted if you need that approach.

**Comment by karolsojko** [comment]
Actually I was wrong @mccrodp - after the PR is merged it should save all the fields in the description, and also break down multiple coma separated values into arrays.
