### ISSUE TITLE
500 letter word limit textarea

### ISSUE THREAD

**Issue by jacekelgda** [jacekelgda/cavalry-bot#6]
There is a letter limit on textarea in slack dialog.  Even though documentation talks about max 3000 letters in one field it actually is 500. There should be a way to bypass this limit.

**Comment by mccrodp** [comment]
Just tested a regular Slack message, it looks like 4000 is upper limit. It is rare, but once I have needed more than this for a post (but it could have been summarised), but likely I'll need more than 500 if possible. Let's see what Slack have to say and if it's an issue we can look into the extra textfield work arounds as a last resort.

**Comment by jacekelgda** [comment]
This issue was just fixed by Slack support team. Works now!
