### ISSUE TITLE
Add lead manager

### ISSUE THREAD

**Issue by jacekelgda** [jacekelgda/cavalry-bot#9]
Each lead should have one manager assigned, Luke, Brad, Jake.

**Comment by mccrodp** [comment]
You mean "Bizdev responsible"? This is what you have as "Bizdev" on the post, then that looks good to me. "Bizdev" or "Bizdev responsible". Interestingly to partners or devs, it would be "Manager", but in Core Team terms, it's one of the *Bizdev* labels 👍
